from .visao_geral import render_visao_geral_receber
from .vencimentos import render_vencimentos_receber
from .clientes import render_clientes
from .categorias import render_categorias_receber
from .evolucao import render_evolucao_receber
from .adiantamentos import render_adiantamentos_receber
from .detalhes import render_detalhes_receber
from .analise_avancada import render_analise_avancada_receber
